import { Event, Volunteer, HourLog, Coordinator } from "@/types"

export const mockVolunteers: Volunteer[] = [
  {
    id: "vol-1",
    name: "John Doe",
    email: "john@example.com",
    phone: "+65 9123 4567",
    skills: ["Driving", "Food Handling"],
    interests: ["Food Bank Services"],
    availability: {},
    commitmentLevel: "flexible",
    totalHours: 0,
    eventsAttended: 0,
    impactPoints: 0,
    verified: false,
  },
]

export const mockCoordinators: Coordinator[] = [
  {
    id: "coord-1",
    name: "Jane Smith",
    email: "jane@heartfelthands.org",
    phone: "+65 9876 5432",
    program: "Food Bank Services",
  },
]

export const mockEvents: Event[] = [
  {
    id: "event-1",
    name: "Weekly Food Pantry Distribution",
    program: "Food Bank Services",
    description: "Help distribute food packages to families in need at our community center.",
    date: "2024-12-07",
    time: "9:00 AM - 1:00 PM",
    duration: 4,
    location: "Heartfelt Hands Community Center, 123 Volunteer Ave",
    locationType: "physical",
    shifts: [
      {
        id: "shift-1",
        roleName: "Morning Setup",
        startTime: "8:00 AM",
        endTime: "10:00 AM",
        volunteersNeeded: 5,
        volunteersRegistered: 2,
        requiredSkills: [],
        minimumAge: 16,
        description: "Set up tables and organize food items",
      },
      {
        id: "shift-2",
        roleName: "Distribution",
        startTime: "9:00 AM",
        endTime: "1:00 PM",
        volunteersNeeded: 15,
        volunteersRegistered: 8,
        requiredSkills: [],
        minimumAge: 14,
        description: "Help distribute food packages to families",
      },
      {
        id: "shift-3",
        roleName: "Cleanup",
        startTime: "12:30 PM",
        endTime: "1:30 PM",
        volunteersNeeded: 5,
        volunteersRegistered: 3,
        requiredSkills: [],
        minimumAge: 16,
        description: "Clean up and organize remaining items",
      },
    ],
    coordinator: mockCoordinators[0],
    requirements: {
      minimumAge: 16,
      skillsNeeded: ["Food Handling"],
      physicalRequirements: "Able to stand for extended periods",
    },
    registrationSettings: {
      opensDaysBefore: 7,
      deadlineHoursBefore: 2,
      enableWaitlist: true,
      maxWaitlistSize: 10,
      allowGroupSignups: false,
      requireApproval: false,
    },
    isRecurring: false,
    status: "published",
  },
  {
    id: "event-2",
    name: "Beach Clean-up Day",
    program: "Environmental Clean-ups",
    description: "Join us for a community beach clean-up to protect our marine environment.",
    date: "2024-12-10",
    time: "8:00 AM - 12:00 PM",
    duration: 4,
    location: "East Coast Park, Beach Area 3",
    locationType: "physical",
    shifts: [
      {
        id: "shift-4",
        roleName: "Beach Cleaner",
        startTime: "8:00 AM",
        endTime: "12:00 PM",
        volunteersNeeded: 20,
        volunteersRegistered: 12,
        requiredSkills: [],
        minimumAge: 12,
        description: "Collect trash and debris from the beach",
      },
    ],
    coordinator: mockCoordinators[0],
    requirements: {
      minimumAge: 12,
      skillsNeeded: [],
      physicalRequirements: "Able to walk on sand and carry bags",
    },
    registrationSettings: {
      opensDaysBefore: 7,
      deadlineHoursBefore: 2,
      enableWaitlist: true,
      maxWaitlistSize: 10,
      allowGroupSignups: false,
      requireApproval: false,
    },
    isRecurring: false,
    status: "published",
  },
  {
    id: "event-3",
    name: "Youth Coding Workshop",
    program: "Community Workshops",
    description: "Teach basic coding skills to underprivileged youth in our community.",
    date: "2024-12-14",
    time: "2:00 PM - 5:00 PM",
    duration: 3,
    location: "Community Learning Center, 456 Education St",
    locationType: "physical",
    shifts: [
      {
        id: "shift-5",
        roleName: "Teaching Assistant",
        startTime: "2:00 PM",
        endTime: "5:00 PM",
        volunteersNeeded: 8,
        volunteersRegistered: 5,
        requiredSkills: ["Teaching/Tutoring"],
        minimumAge: 18,
        description: "Assist instructors and help students with coding exercises",
      },
    ],
    coordinator: mockCoordinators[0],
    requirements: {
      minimumAge: 18,
      skillsNeeded: ["Teaching/Tutoring"],
      physicalRequirements: "None",
    },
    registrationSettings: {
      opensDaysBefore: 7,
      deadlineHoursBefore: 2,
      enableWaitlist: true,
      maxWaitlistSize: 10,
      allowGroupSignups: false,
      requireApproval: false,
    },
    isRecurring: false,
    status: "published",
  },
  {
    id: "event-4",
    name: "Elderly Care Visit",
    program: "Elderly Care",
    description: "Spend time with elderly residents, play games, and provide companionship.",
    date: "2024-12-15",
    time: "10:00 AM - 2:00 PM",
    duration: 4,
    location: "Sunshine Senior Home, 789 Care Ave",
    locationType: "physical",
    shifts: [
      {
        id: "shift-6",
        roleName: "Companion",
        startTime: "10:00 AM",
        endTime: "2:00 PM",
        volunteersNeeded: 10,
        volunteersRegistered: 6,
        requiredSkills: [],
        minimumAge: 16,
        description: "Engage with residents through activities and conversation",
      },
    ],
    coordinator: mockCoordinators[0],
    requirements: {
      minimumAge: 16,
      skillsNeeded: [],
      physicalRequirements: "None",
    },
    registrationSettings: {
      opensDaysBefore: 7,
      deadlineHoursBefore: 2,
      enableWaitlist: true,
      maxWaitlistSize: 10,
      allowGroupSignups: false,
      requireApproval: false,
    },
    isRecurring: false,
    status: "published",
  },
  {
    id: "event-5",
    name: "Youth Sports Day",
    program: "Youth Programs",
    description: "Organize and supervise sports activities for children aged 8-15.",
    date: "2024-12-16",
    time: "9:00 AM - 3:00 PM",
    duration: 6,
    location: "Community Sports Complex, 321 Sports Rd",
    locationType: "physical",
    shifts: [
      {
        id: "shift-7",
        roleName: "Activity Leader",
        startTime: "9:00 AM",
        endTime: "3:00 PM",
        volunteersNeeded: 12,
        volunteersRegistered: 7,
        requiredSkills: [],
        minimumAge: 18,
        description: "Lead sports activities and ensure safety",
      },
    ],
    coordinator: mockCoordinators[0],
    requirements: {
      minimumAge: 18,
      skillsNeeded: [],
      physicalRequirements: "Able to participate in physical activities",
    },
    registrationSettings: {
      opensDaysBefore: 7,
      deadlineHoursBefore: 2,
      enableWaitlist: true,
      maxWaitlistSize: 10,
      allowGroupSignups: false,
      requireApproval: false,
    },
    isRecurring: false,
    status: "published",
  },
]

export const mockHourLogs: HourLog[] = [
  {
    id: "log-1",
    volunteerId: "vol-1",
    eventId: "event-1",
    shiftId: "shift-2",
    checkInTime: "2024-12-02T09:00:00",
    checkOutTime: "2024-12-02T13:30:00",
    hours: 4.5,
    tasksPerformed: ["Food sorting", "Distribution"],
    notes: "Great experience!",
    status: "pending",
    submittedAt: "2024-12-02T14:00:00",
  },
]

export const mockPrograms = [
  "Food Bank Services",
  "Environmental Clean-ups",
  "Community Workshops",
  "Youth Programs",
  "Elderly Care",
]

export const mockSkills = [
  "Driving (has valid license)",
  "Cooking/Food Preparation",
  "Teaching/Tutoring",
  "Graphic Design",
  "Photography",
  "Physical Labor/Heavy Lifting",
  "First Aid Certified",
  "Language Skills",
  "Administrative/Clerical",
  "Event Planning",
]

export const mockInterests = [
  "Food Bank Services",
  "Environmental Clean-ups",
  "Community Workshops",
  "Elderly Care",
  "Youth Programs",
]

export const mockLanguages = ["Mandarin", "Malay", "Tamil", "English", "Hindi"]

